os:
    ubuntu

language: python
python:
    - 2.7
    - 3.6

before_install:
    - sudo apt-get update 
    - sudo apt install cmake pkg-config
    - sudo apt install libhwloc-dev
    - sudo apt install opencl-headers
    - sudo apt install ocl-icd-opencl-dev

install:
    - wget https://github.com/pocl/pocl/archive/v1.2.tar.gz
    - tar xf v1.2.tar.gz
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_ICD=ON ../pocl-1.2
    - make -j`nproc`
    - sudo make install
    - export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
    - clinfo
    - sudo mkdir -p /etc/OpenCL/vendors/
    - sudo cp /usr/local/etc/OpenCL/vendors/pocl.icd /etc/OpenCL/vendors/
    - clinfo
    - pip install pyopencl
    - python -c 'import pyopencl as cl'
    - pip install beaker tox tox-travis

script:
    - tox
